#!/usr/bin/env bash
#
# install.sh — one-shot installer for the DiskHealth collection agent.
#
# Intended to be piped straight into a root shell, e.g.:
#
#   curl -fsSL https://raw.githubusercontent.com/YOURORG/DiskHealth/main/install.sh \
#     | sudo bash -s -- \
#         --endpoint https://disk-health.example.com \
#         --token tok_xxxxxxxxxxxxxxxx
#
# It installs dependencies, drops the collection script, writes the device
# config (with the per-device bearer token), and registers a nightly cron job
# at a randomized minute so fleets don't all post at once.

set -euo pipefail

# Where to fetch getdiskhealth.sh from. Override with --repo-raw if you fork.
REPO_RAW="${REPO_RAW:-https://raw.githubusercontent.com/YOURORG/DiskHealth/main}"

ENDPOINT=""
TOKEN=""
HOUR=2            # default nightly hour (local time)
RUN_NOW=1

usage() {
  cat <<EOF
Usage: install.sh --endpoint URL --token TOKEN [options]

  --endpoint URL    Central ingest base URL (e.g. https://disk-health.example.com)
  --token TOKEN     Per-device bearer token (mint one on the server)
  --hour N          Nightly run hour, 0-23 local time (default: 2)
  --repo-raw URL    Base raw URL to fetch getdiskhealth.sh from
  --no-run          Do not run a collection immediately after install
  -h, --help        Show this help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --endpoint) ENDPOINT="$2"; shift 2;;
    --token)    TOKEN="$2"; shift 2;;
    --hour)     HOUR="$2"; shift 2;;
    --repo-raw) REPO_RAW="$2"; shift 2;;
    --no-run)   RUN_NOW=0; shift;;
    -h|--help)  usage; exit 0;;
    *) echo "Unknown arg: $1" >&2; usage; exit 1;;
  esac
done

[[ $EUID -eq 0 ]] || { echo "Please run as root (use sudo)." >&2; exit 1; }
[[ -n "$ENDPOINT" ]] || { echo "--endpoint is required" >&2; exit 1; }
[[ -n "$TOKEN" ]] || { echo "--token is required" >&2; exit 1; }
ENDPOINT="${ENDPOINT%/}"   # strip trailing slash

echo "==> Installing dependencies (smartmontools, jq, curl)"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq smartmontools jq curl >/dev/null

echo "==> Creating directories"
install -d -m 755 /opt/disk-health
install -d -m 700 /etc/disk-health
install -d -m 700 /var/lib/disk-health/spool

echo "==> Fetching collection script"
if ! curl -fsSL "$REPO_RAW/getdiskhealth.sh" -o /opt/disk-health/getdiskhealth.sh; then
  echo "Failed to download getdiskhealth.sh from $REPO_RAW" >&2
  exit 1
fi
chmod 755 /opt/disk-health/getdiskhealth.sh

echo "==> Writing device config"
umask 077
cat > /etc/disk-health/config <<EOF
# DiskHealth device config — generated by install.sh on $(date -u +%FT%TZ)
ENDPOINT="$ENDPOINT"
TOKEN="$TOKEN"
EOF
chmod 600 /etc/disk-health/config

echo "==> Registering nightly cron job"
MIN=$(( RANDOM % 60 ))   # randomize minute to avoid a fleet-wide thundering herd
cat > /etc/cron.d/disk-health <<EOF
# DiskHealth nightly collection — managed by install.sh
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
$MIN $HOUR * * * root /opt/disk-health/getdiskhealth.sh >> /var/log/disk-health.log 2>&1
EOF
chmod 644 /etc/cron.d/disk-health
echo "    scheduled daily at ${HOUR}:$(printf '%02d' "$MIN") (local time)"

if [[ "$RUN_NOW" -eq 1 ]]; then
  echo "==> Running an initial collection now"
  if /opt/disk-health/getdiskhealth.sh; then
    echo "==> Success. DiskHealth agent installed and reporting."
  else
    echo "!! Initial run failed (see output above). The cron job is still installed;"
    echo "   payloads will be spooled and retried. Check ENDPOINT/TOKEN reachability."
    exit 1
  fi
else
  echo "==> Installed. First report will run tonight."
fi
